#Requires -Version 5.1
<#
.SYNOPSIS
  将 backend 打成可拷贝到 IIS 服务器部署的目录（含 app、requirements、web.config、说明）。

.DESCRIPTION
  输出目录默认为 backend/iis-publish-artifacts/（与仓库内 venv 无关，服务器需自行创建 venv 并 pip install -r requirements.txt）。

.PARAMETER BackendRoot
  服务器上将要放置本发布包的**绝对路径**（用于生成 web.config 中的 python 与 PYTHONPATH）。
  若省略，则 web.config 中使用占位符 BACKEND_ROOT_PLACEHOLDER，部署前需手动替换。

.PARAMETER OutputDir
  输出目录，默认：backend/iis-publish-artifacts

.PARAMETER Zip
  额外生成 iis-backend-publish.zip（位于 backend 目录下）

.EXAMPLE
  .\scripts\publish-for-iis.ps1 -BackendRoot "D:\Sites\PythonBlog\backend"

.EXAMPLE
  .\scripts\publish-for-iis.ps1 -Zip
#>
[CmdletBinding()]
param(
    [string] $BackendRoot = "",
    [string] $OutputDir = "",
    [switch] $Zip
)

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$BackendDir = (Resolve-Path (Join-Path $ScriptDir "..")).Path

if (-not $OutputDir) {
    $OutputDir = Join-Path $BackendDir "iis-publish-artifacts"
} else {
    $OutputDir = (Resolve-Path $OutputDir).Path
}

if (Test-Path $OutputDir) {
    Remove-Item $OutputDir -Recurse -Force
}
New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null

$AppSrc = Join-Path $BackendDir "app"
if (-not (Test-Path $AppSrc)) {
    throw "找不到 app 目录: $AppSrc"
}

Write-Host "复制 app/ -> $OutputDir\app" -ForegroundColor Cyan
Copy-Item $AppSrc (Join-Path $OutputDir "app") -Recurse -Force
Get-ChildItem (Join-Path $OutputDir "app") -Recurse -Directory -Filter "__pycache__" -ErrorAction SilentlyContinue |
    ForEach-Object { Remove-Item $_.FullName -Recurse -Force -ErrorAction SilentlyContinue }

Copy-Item (Join-Path $BackendDir "requirements.txt") (Join-Path $OutputDir "requirements.txt") -Force

$IisEntry = Join-Path $BackendDir "iis_entry.py"
if (Test-Path $IisEntry) {
    Copy-Item $IisEntry (Join-Path $OutputDir "iis_entry.py") -Force
}

# web.config
$pyExePlaceholder = "BACKEND_ROOT_PLACEHOLDER\venv\Scripts\python.exe"
$pyPathPlaceholder = "BACKEND_ROOT_PLACEHOLDER"
if ($BackendRoot) {
    $br = $BackendRoot.TrimEnd('\')
    $pyExePlaceholder = Join-Path $br "venv\Scripts\python.exe"
    $pyPathPlaceholder = $br
}

function Escape-XmlAttr([string]$s) {
    if ($null -eq $s) { return "" }
    return ($s -replace '&', '&amp;' -replace '"', '&quot;')
}

$exeEsc = Escape-XmlAttr $pyExePlaceholder
$pathEsc = Escape-XmlAttr $pyPathPlaceholder

$webConfig = @"
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpPlatformHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
    </handlers>
    <httpPlatform
      processPath="$exeEsc"
      arguments="-m iis_entry"
      stdoutLogEnabled="true"
      stdoutLogFile=".\logs\stdout"
      startupTimeLimit="120"
      startupRetryCount="10">
      <environmentVariables>
        <environmentVariable name="PYTHONPATH" value="$pathEsc" />
      </environmentVariables>
    </httpPlatform>
  </system.webServer>
</configuration>
"@

$webConfigPath = Join-Path $OutputDir "web.config"
Set-Content -Path $webConfigPath -Value $webConfig -Encoding UTF8
Write-Host "已写入 web.config" -ForegroundColor Cyan

$readme = @"
IIS publish package (Blog API)
==============================

Generated by backend/scripts/publish-for-iis.ps1. Copy this folder to the server.

Steps:

1. Place this folder at the target path, e.g. D:\Sites\PythonBlog\backend (must match PYTHONPATH in web.config).

2. If web.config still contains BACKEND_ROOT_PLACEHOLDER, replace with the real backend absolute path (processPath and PYTHONPATH).

3. In backend folder:
   python -m venv venv
   venv\Scripts\pip install -r requirements.txt

4. Copy .env from .env.example and set DATABASE_URL, SECRET_KEY, etc.

5. Create folder logs (for stdout logs from web.config).

6. IIS site physical path = this backend folder; binding e.g. www.blogapi.com:80.

7. Install HttpPlatformHandler.

web.config uses: python -m iis_entry (reads HTTP_PLATFORM_PORT from IIS). If you see 502.3, see docs/后端-IIS部署说明.md section 502.3.

Health: http://your-host:port/api/health
"@

# 使用 ASCII 文件名，避免部分服务器上中文文件名乱码
$utf8Bom = New-Object System.Text.UTF8Encoding $true
[System.IO.File]::WriteAllText((Join-Path $OutputDir "README-IIS-Deploy.txt"), $readme, $utf8Bom)

# 可选：附带 .env.example 供改名
$envEx = Join-Path $BackendDir ".env.example"
if (Test-Path $envEx) {
    Copy-Item $envEx (Join-Path $OutputDir ".env.example") -Force
}

Write-Host "完成: $OutputDir" -ForegroundColor Green

if ($Zip) {
    $zipPath = Join-Path $BackendDir "iis-backend-publish.zip"
    if (Test-Path $zipPath) { Remove-Item $zipPath -Force }
    Compress-Archive -Path $OutputDir -DestinationPath $zipPath
    Write-Host "已打包: $zipPath" -ForegroundColor Green
}
